name: teledartgame
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  teledart: ^0.6.1
  http: ^1.2.1
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
